services:
  postgres:
    image: postgres:15-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: orez
      POSTGRES_PASSWORD: 1231231
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: